/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 capsule.gltf --transform
Author: The Smithsonian Institution (https://sketchfab.com/Smithsonian)
License: CC0-1.0 (http://creativecommons.org/publicdomain/zero/1.0/)
Source: https://sketchfab.com/3d-models/apollo-11-command-module-combined-372bb6781922471cada4e0a9bd5c61fb
Title: Apollo 11 Command Module (Combined)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/capsule-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.Object_3.geometry} material={materials['ml.001']} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.Object_5.geometry} material={materials['ml.002']} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.Object_8.geometry} material={materials['ml.003']} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.Object_14.geometry} material={materials['ml.004']} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
      <mesh geometry={nodes.Object_17.geometry} material={materials['ml.005']} rotation={[-Math.PI / 2, 0, 0]} scale={0.014} />
    </group>
  )
}

useGLTF.preload('/capsule-transformed.glb')
