/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 spaceport.gltf --transform
Author: Scilence (https://sketchfab.com/Scilence)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/spaceport-low-poly-19a283dbb1864d56ac9c99edaabc5314
Title: Spaceport, Low-Poly
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/spaceport-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Spaceport_24_Blue_composite__0.geometry} material={materials.Blue_composite} position={[-0.014, 21.257, 390.837]} rotation={[-Math.PI / 2, 0, 0]} scale={[76.596, 1.578, 1.578]} />
      <mesh geometry={nodes.Spaceport_24_Mettalic_composite_0.geometry} material={materials.Mettalic_composite} position={[-0.014, 21.257, 390.837]} rotation={[-Math.PI / 2, 0, 0]} scale={[76.596, 1.578, 1.578]} />
      <mesh geometry={nodes.Spaceport_24_concrete_1_0.geometry} material={materials.concrete_1} position={[-0.014, 21.257, 390.837]} rotation={[-Math.PI / 2, 0, 0]} scale={[76.596, 1.578, 1.578]} />
      <mesh geometry={nodes.Spaceport_24_Working_area_0.geometry} material={materials.Working_area} position={[-0.014, 21.257, 390.837]} rotation={[-Math.PI / 2, 0, 0]} scale={[76.596, 1.578, 1.578]} />
    </group>
  )
}

useGLTF.preload('/spaceport-transformed.glb')
